# Generated by Django 4.2.10 on 2024-04-12 06:28

import RecognitionApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecognitionApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=255, null=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=RecognitionApp.models.customer_directory_path, verbose_name='Photo'),
        ),
    ]
