# Generated by Django 4.2.10 on 2024-04-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecognitionApp', '0002_customer_username_alter_customer_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='photo',
        ),
        migrations.AddField(
            model_name='customer',
            name='photo1',
            field=models.ImageField(null=True, upload_to='customer_photos/', verbose_name='Photo 1'),
        ),
        migrations.AddField(
            model_name='customer',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='customer_photos/', verbose_name='Photo 2'),
        ),
        migrations.AddField(
            model_name='customer',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='customer_photos/', verbose_name='Photo 3'),
        ),
    ]
